import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import CompanyTabs from "@/components/CompanyTabs";
import RoleSwitcher from "@/components/RoleSwitcher";
import ProjectTabs from "@/components/ProjectTabs";
import { RoleProvider } from "@/components/RoleContext";
import { OrgProvider } from "@/components/OrgContext";
import { ScopeProvider } from "@/components/ScopeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex h-full flex-col bg-[#0b0e1a] text-white">
        <RoleProvider>
          <OrgProvider>
            <ScopeProvider>
              <RoleSwitcher />
              <div className="flex flex-1 overflow-hidden">
                <Sidebar />
                <div className="flex flex-1 flex-col overflow-hidden">
                  <CompanyTabs />
                  <ProjectTabs />
                  {children}
                </div>
              </div>
            </ScopeProvider>
          </OrgProvider>
        </RoleProvider>
      </body>
    </html>
  );
}
